# Generated by Django 3.2.9 on 2021-11-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopBrands', models.CharField(max_length=50)),
                ('Luxury', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
