# Generated by Django 3.2.9 on 2021-11-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_filter_top_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_top',
            name='img',
            field=models.ImageField(height_field=150, null='true', upload_to='img/', width_field=150),
        ),
    ]
