# Generated by Django 3.2.9 on 2021-11-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_companyname_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='filter_luxury',
            name='Price',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='filter_top',
            name='Price',
            field=models.IntegerField(max_length=20),
        ),
    ]
