# Generated by Django 3.2.9 on 2021-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20211124_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_luxury',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='filter_top',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
