# Generated by Django 3.2.9 on 2021-11-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20211124_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand_luxury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(default='', upload_to='media/luxury/logo')),
            ],
        ),
        migrations.CreateModel(
            name='brand_top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(default='', upload_to='media/top/logo')),
            ],
        ),
    ]
