# Generated by Django 3.2.9 on 2021-11-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_brand_luxury_brand_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('img1', models.ImageField(default='', upload_to='media/carinfo')),
                ('img2', models.ImageField(default='', upload_to='media/carinfo')),
                ('img3', models.ImageField(default='', upload_to='media/carinfo')),
                ('img4', models.ImageField(default='', upload_to='media/carinfo')),
                ('body_type', models.CharField(max_length=150)),
                ('mileage', models.CharField(max_length=150)),
                ('fuel_type', models.CharField(max_length=150)),
                ('transmission', models.CharField(max_length=150)),
                ('sitting', models.CharField(max_length=150)),
                ('sunroof', models.CharField(max_length=150)),
                ('tank_capicity', models.CharField(max_length=150)),
            ],
        ),
    ]
