# Generated by Django 3.2.9 on 2021-11-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_filter_top_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='filter_top',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
